Repository team1-monew/sb02-monew-team1, pull requests merged in 2025-06, with the labels that each got.

#13 feat: KAN-16 사용자 등록 및 로그인
  src/main/java/com/team1/monew/user/controller/UserController.java
  src/main/java/com/team1/monew/user/dto/UserDto.java
  src/main/java/com/team1/monew/user/dto/UserLoginRequest.java
  src/main/java/com/team1/monew/user/dto/UserRegisterRequest.java
  src/main/java/com/team1/monew/user/entity/User.java
  src/main/java/com/team1/monew/user/mapper/UserMapper.java
  src/main/java/com/team1/monew/user/repository/UserRepository.java
  src/main/java/com/team1/monew/user/service/UserService.java
  src/main/java/com/team1/monew/user/service/UserServiceImpl.java
  src/test/java/com/team1/monew/MonewApplicationTests.java
  src/test/java/com/team1/monew/user/UserApiIntegrationTest.java
  src/test/java/com/team1/monew/user/service/UserServiceImplTest.java
Labels: feat

#20 feat: KAN-52 댓글 좋아요 기능 추가
  src/main/java/com/team1/monew/comment/controller/CommentController.java
  src/main/java/com/team1/monew/comment/dto/CommentLikeDto.java
  src/main/java/com/team1/monew/comment/entity/CommentLike.java
  src/main/java/com/team1/monew/comment/mapper/CommentLikeMapper.java
  src/main/java/com/team1/monew/comment/repository/CommentLikeRepository.java
  src/main/java/com/team1/monew/comment/service/CommentLikeService.java
  src/main/java/com/team1/monew/comment/service/CommentLikeServiceImpl.java
  src/test/java/com/team1/monew/comment/repository/CommentLikeRepositoryTest.java
Labels: feat

#22 feat: KAN-51 댓글 목록 조회
  build.gradle
  src/main/java/com/team1/monew/comment/controller/CommentController.java
  src/main/java/com/team1/monew/comment/dto/CommentOrderBy.java
  src/main/java/com/team1/monew/comment/dto/CommentSearchCondition.java
  src/main/java/com/team1/monew/comment/mapper/CommentLikeMapper.java
  src/main/java/com/team1/monew/comment/mapper/CommentMapper.java
  src/main/java/com/team1/monew/comment/mapper/PageResponseMapper.java
  src/main/java/com/team1/monew/comment/repository/CommentRepository.java
  src/main/java/com/team1/monew/comment/repository/CommentRepositoryCustom.java
  src/main/java/com/team1/monew/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/team1/monew/comment/service/CommentService.java
  src/main/java/com/team1/monew/comment/service/CommentServiceImpl.java
  src/main/java/com/team1/monew/comment/service/usecase/FindCommentsUseCase.java
  src/main/java/com/team1/monew/common/dto/CursorPageResponse.java
  src/main/java/com/team1/monew/config/QueryDslConfig.java
  src/test/java/com/team1/monew/comment/repository/CommentLikeRepositoryTest.java
  src/test/java/com/team1/monew/comment/repository/CommentRepositoryImplTest.java
Labels: feat

#23 feat: KAN-18 인증 권한 및 유효성 검사
  build.gradle
  src/main/java/com/team1/monew/exception/ErrorCode.java
  src/main/java/com/team1/monew/exception/ErrorResponse.java
  src/main/java/com/team1/monew/exception/GlobalExceptionHandler.java
  src/main/java/com/team1/monew/security/CustomUserDetails.java
  src/main/java/com/team1/monew/security/HeaderUserAuthenticationFilter.java
  src/main/java/com/team1/monew/security/SecurityConfig.java
  src/main/java/com/team1/monew/security/SecurityPathUtil.java
  src/main/java/com/team1/monew/user/controller/UserController.java
  src/main/java/com/team1/monew/user/dto/UserLoginRequest.java
  src/main/java/com/team1/monew/user/dto/UserRegisterRequest.java
  src/main/java/com/team1/monew/user/dto/UserUpdateRequest.java
  src/main/java/com/team1/monew/user/service/UserServiceImpl.java
  src/test/java/com/team1/monew/security/HeaderUserAuthenticationFilterTest.java
  src/test/java/com/team1/monew/security/SecurityConfigIntegrationTest.java
  src/test/java/com/team1/monew/user/UserApiIntegrationTest.java
Labels: feat

#33 fix: KAN-231 사용자 관리 수정
  src/main/java/com/team1/monew/security/auth/CustomUserDetails.java
  src/main/java/com/team1/monew/security/config/SecurityConfig.java
  src/main/java/com/team1/monew/security/filter/ExceptionHandlingFilter.java
  src/main/java/com/team1/monew/security/filter/HeaderUserAuthenticationFilter.java
  src/main/java/com/team1/monew/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/team1/monew/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/team1/monew/security/support/ErrorResponseWriter.java
  src/main/java/com/team1/monew/security/util/SecurityPathUtil.java
  src/main/java/com/team1/monew/user/controller/UserController.java
  src/main/java/com/team1/monew/user/dto/UserRegisterRequest.java
  src/main/java/com/team1/monew/user/entity/User.java
  src/main/java/com/team1/monew/user/service/UserServiceImpl.java
  src/test/java/com/team1/monew/security/HeaderUserAuthenticationFilterTest.java
Labels: fix

#39 feat: KAN-67 댓글 좋아요 알림 트리거
  build.gradle
  src/main/java/com/team1/monew/MonewApplication.java
  src/main/java/com/team1/monew/comment/event/CommentLikedEvent.java
  src/main/java/com/team1/monew/comment/service/CommentLikeServiceImpl.java
  src/main/java/com/team1/monew/notification/dto/ResourceType.java
  src/main/java/com/team1/monew/notification/entity/Notification.java
  src/main/java/com/team1/monew/notification/event/NotificationEventListener.java
  src/main/java/com/team1/monew/notification/repository/NotificationRepository.java
  src/main/java/com/team1/monew/notification/service/NotificationService.java
  src/main/java/com/team1/monew/notification/service/NotificationServiceImpl.java
  src/test/java/com/team1/monew/notification/event/CommentLikedEventAsyncTest.java
  src/test/java/com/team1/monew/notification/service/NotificationServiceImplTest.java
Labels: feat

#42 feat: KAN-68 관심사 관련 기사 등록 시 알림 생성 트리거
  src/main/java/com/team1/monew/article/event/NewArticlesCollectedEvent.java
  src/main/java/com/team1/monew/article/service/ArticleServiceImpl.java
  src/main/java/com/team1/monew/notification/event/NotificationEventListener.java
  src/main/java/com/team1/monew/notification/service/NotificationService.java
  src/main/java/com/team1/monew/notification/service/NotificationServiceImpl.java
  src/main/java/com/team1/monew/subscription/repository/SubscriptionRepository.java
  src/test/java/com/team1/monew/notification/event/NewArticlesCollectedEventAsyncTest.java
  src/test/java/com/team1/monew/notification/service/NotificationServiceImplTest.java
Labels: feat

#43 modify: KAN-266 코드 리팩토링
  src/main/java/com/team1/monew/article/config/ArticleBackupJobConfig.java
  src/main/java/com/team1/monew/article/controller/ArticleController.java
  src/main/java/com/team1/monew/article/repository/ArticleRepositoryCustom.java
  src/main/java/com/team1/monew/article/repository/ArticleRepositoryCustomImpl.java
  src/main/java/com/team1/monew/article/service/ArticleService.java
  src/main/java/com/team1/monew/article/service/ArticleServiceImpl.java
Labels: modify

#44 feat: KAN-273 뉴스 기사 복구 기능 구현
  src/main/java/com/team1/monew/article/controller/ArticleController.java
  src/main/java/com/team1/monew/article/entity/Article.java
  src/main/java/com/team1/monew/article/mapper/ArticleMapper.java
  src/main/java/com/team1/monew/article/service/ArticleServiceImpl.java
  src/main/java/com/team1/monew/common/S3Util.java
Labels: feat

#48 test: KAN-304 테스트 코드 작성
  src/test/java/com/team1/monew/article/config/ArticleBackupJobConfigTest.java
  src/test/java/com/team1/monew/article/service/ArticleServiceImplTest.java
Labels: test

#47 feat: KAN-258 알림 확인
  src/main/java/com/team1/monew/notification/controller/NotificationController.java
  src/main/java/com/team1/monew/notification/repository/NotificationRepository.java
  src/main/java/com/team1/monew/notification/service/NotificationService.java
  src/main/java/com/team1/monew/notification/service/NotificationServiceImpl.java
  src/test/java/com/team1/monew/notification/repository/NotificationRepositoryTest.java
  src/test/java/com/team1/monew/notification/service/NotificationServiceImplTest.java
Labels: feat

#58 fix: KAN-329 알림 관리 수정
  src/main/java/com/team1/monew/article/service/ArticleServiceImpl.java
  src/main/java/com/team1/monew/notification/config/NotificationCleanupJobConfig.java
  src/main/java/com/team1/monew/notification/mapper/NotificationPageResponseMapper.java
Labels: fix

#61 modify: KAN-345-활동내역-관리-수정
  src/main/java/com/team1/monew/article/service/ArticleServiceImpl.java
Labels: modify

#65 test: KAN-334 사용자 관리 테스트 코드
  src/test/java/com/team1/monew/user/UserApiIntegrationTest.java
  src/test/java/com/team1/monew/user/service/UserServiceImplTest.java
Labels: test

#67 test: KAN-364 알림 관리 테스트 코드
  src/test/java/com/team1/monew/notification/NotificationIntegrationTest.java
  src/test/java/com/team1/monew/notification/repository/NotificationRepositoryTest.java
  src/test/java/com/team1/monew/notification/service/NotificationServiceImplTest.java
Labels: test

#69 test: KAN-336 댓글 관리 테스트 코드
  build.gradle
  src/test/java/com/team1/monew/comment/CommentIntegrationTest.java
  src/test/java/com/team1/monew/comment/CommentLikeIntegrationTest.java
  src/test/java/com/team1/monew/comment/repository/CommentLikeRepositoryTest.java
  src/test/java/com/team1/monew/comment/repository/CommentRepositoryImplTest.java
  src/test/java/com/team1/monew/comment/service/CommentLikeServiceImplTest.java
  src/test/java/com/team1/monew/comment/service/CommentServiceImplTest.java
Labels: test

#70 test: KAN-328 활동 내역 관리 테스트 코드
  src/test/java/com/team1/monew/useractivity/integration/UserActivityIntegrationTest.java
  src/test/java/com/team1/monew/useractivity/scheduler/service/ArticleViewActivityBatchServiceTest.java
  src/test/java/com/team1/monew/useractivity/scheduler/service/CommentActivityBatchServiceTest.java
  src/test/java/com/team1/monew/useractivity/scheduler/service/CommentLikeActivityBatchServiceTest.java
  src/test/java/com/team1/monew/useractivity/scheduler/service/SubscriptionActivityBatchServiceTest.java
Labels: test

#73 feat: KAN-380 댓글 수정 시 이벤트 기반 활동 내역 수정 구현
  src/main/java/com/team1/monew/comment/event/CommentActivityEditedEvent.java
  src/main/java/com/team1/monew/comment/event/listener/CommentActivityEventListener.java
  src/main/java/com/team1/monew/comment/service/CommentServiceImpl.java
  src/test/java/com/team1/monew/comment/CommentIntegrationTest.java
Labels: feat

#81 modify: KAN-399 articleView 엔티티 수정
  src/main/java/com/team1/monew/article/entity/ArticleView.java
Labels: modify

#86 fix: KAN-398 기사 수집 시 알림 버그 수정
  src/main/java/com/team1/monew/article/service/ArticleServiceImpl.java
  src/main/java/com/team1/monew/notification/controller/NotificationController.java
Labels: fix
